# This just categorizes all the fandoms
# Needs to be updated when encountering new fandoms
FANDOM_CATEGORIES_BY_YEAR = [
    { # 2013
    'All Time Low': 'Music/RPF',
    'Attack on Titan': 'Anime/Manga',
    'Castle': 'TV',
    'EXO': 'Music/RPF',
    'Free!': 'Anime/Manga',
    'Glee': 'TV',
    'Hannibal': 'TV',
    'Hetalia': 'Anime',
    'Merlin': 'TV',
    'One Direction': 'Music/RPF',
    'Sherlock': 'TV',
    'Supernatural': 'TV',
    'Teen Wolf': 'TV',
    'The Originals': 'TV',
    'The Vampire Diaries': 'Books/TV',
    'actors': 'RPF',
    },
    {# 2014
    'Arrow': 'Comics/TV',
    'Attack on Titan': 'Anime/Manga',
    'Free!': 'Anime',
    'Frozen': 'Animation/Movies',
    'Glee': 'TV',
    'Once Upon a Time': 'TV',
    'One Direction': 'Music/RPF',
    'Sherlock': 'TV',
    'Supernatural': 'TV',
    'Teen Wolf': 'TV',
    'The Hunger Games': 'Books/Movies',
    'The Originals': 'TV',
    'The Vampire Diaries': 'Books/TV',
    'YouTubers': 'Internet/RPF',
    'actors': 'RPF',
    'celebrities': 'RPF',
    'the Marvel universe': 'Comics/Movies/TV',
    },
    {# 2015
    '5 Seconds of Summer': 'Music/RPF',
    'Arrow': 'Comics/TV',
    'Attack on Titan': 'Anime/Manga',
    'Carmilla': 'Web Series',
    'Fairy Tail': 'Anime/Manga',
    'Free!': 'Anime',
    'Glee': 'TV',
    'Haikyuu!!': 'Anime/Manga',
    'Hannibal': 'TV',
    'Naruto': 'Anime/Manga',
    'Once Upon a Time': 'TV',
    'One Direction': 'Music/RPF',
    'Sherlock': 'TV',
    'Steven Universe': 'Animation',
    'Supernatural': 'TV',
    'Teen Wolf': 'TV',
    'The 100': 'TV',
    'The Legend of Korra': 'Animation',
    'YouTubers': 'Internet/RPF',
    'actors': 'RPF',
    'the Marvel universe': 'Comics/Movies/TV',
    },
    {# 2016
    'Arrow': 'Comics/TV',
    'Captain America: Civil war': 'Comics/Movies',
    'Fairy Tail': 'Anime/Manga',
    'Fifth Harmony': 'Music/RPF',
    'Haikyuu!!': 'Anime/Manga',
    'Miraculous: Tales of Ladybug & Cat Noir': 'Animation',
    'Naruto': 'Anime/Manga',
    'Once Upon a Time': 'TV',
    'One Direction': 'Music/RPF',
    'Overwatch': 'Video Games',
    'Shadowhunters': 'Books/TV',
    'Star Wars: The Force Awakens': 'Movies',
    'Supernatural': 'TV',
    'Teen Wolf': 'TV',
    'The 100': 'TV',
    'Voltron: Legendary Defender': 'Animation',
    'YouTubers': 'Internet/RPF',
    },
    {# 2017
    'BTS': 'Music/RPF',
    'Boku No Hero Academia': 'Anime/Manga',
    'Fairy Tail': 'Anime/Manga',
    'Fifth Harmony': 'Music/RPF',
    'Game of Thrones': 'Books/TV',
    'Naruto': 'Anime/Manga',
    'Overwatch': 'Video Games',
    'Riverdale': 'Comics/TV',
    'Shadowhunters': 'Books/TV',
    'Sherlock': 'TV',
    'Skam': 'TV',
    'Star Wars: The Force Awakens': 'Movies',
    'Supergirl': 'Comics/TV',
    'Supernatural': 'TV',
    'Teen Wolf': 'TV',
    'The 100': 'TV',
    'Voltron: Legendary Defender': 'Animation',
    'Wynonna Earp': 'Comics/TV',
    'YouTubers': 'Internet/RPF',
    'Yuri!!! on Ice': 'Anime',
    'actors': 'RPF',
    'the Harry Potter universe': 'Books/Movies',
    },
    {# 2018
    'Adventure Time': 'Animation',
    'Agents of S.H.I.E.L.D.': 'Comics/TV',
    'Andi Mack': 'TV',
    'Arrow': 'Comics/TV',
    'Attack on Titan': 'Anime/Manga',
    'BTS': 'Music/RPF',
    'Boku no Hero Academia': 'Anime/Manga',
    'Brooklyn Nine-Nine': 'TV',
    'BuzzFeed Unsolved': 'Web Series',
    'Canadian ice dancers': 'RPF/Sports',
    'Carry On': 'Books',
    'Detroit: Become Human': 'Video Games',
    'EXO': 'Music/RPF',
    'Fairy Tail': 'Anime/Manga',
    'Fifth Harmony': 'Music/RPF',
    'Game of Thrones': 'Books/TV',
    'Gotham': 'Comics/TV',
    'Haikyuu!!': 'Anime/Manga',
    'Hannibal': 'TV',
    'It': 'Books/Movies',
    'Merlin': 'TV',
    'Miraculous: Tales of Ladybug & Cat Noir': 'Animation',
    'Naruto': 'Anime/Manga',
    'One Direction': 'Music/RPF',
    'Overwatch': 'Video Games',
    'Pitch Perfect': 'Movies',
    'RWBY': 'Animation',
    'Riverdale': 'Comics/TV',
    'Runaways': 'Comics/TV',
    'Shadowhunters': 'Books/TV',
    'Shallura': 'Animation',
    'Sherlock': 'TV',
    'South Park': 'Animation',
    'Star Trek': 'Movies/TV',
    'Star vs. the Forces of Evil': 'Animation',
    'Steven Universe': 'Animation',
    'Stranger Things': 'TV',
    'Supergirl': 'Comics/TV',
    'Supernatural': 'TV',
    'Teen Wolf': 'TV',
    'The 100': 'TV',
    'The Bold Type': 'TV',
    'The Flash': 'Comics/TV',
    'The Legend of Korra': 'Animation',
    'The Originals': 'TV',
    'Thomas Sanders': 'Internet/RPF',
    'Voltron: Legendary Defender': 'Animation',
    'Wynonna Earp': 'Comics/TV',
    'YouTubers': 'Internet/RPF',
    'Yuri!!! on Ice': 'Anime',
    'actors': 'RPF',
    'celebrities': 'RPF',
    'the Harry Potter universe': 'Books/Movies',
    'the Marvel universe': 'Comics/Movies/TV',
    'the Percy Jackson universe': 'Books/Movies',
    'the Star Wars universe': 'Movies/TV/Animation',
    },
    {# 2019
    'Actors': 'RPF',
    'Adventure Time': 'Animation',
    'Amar a muerte': 'TV',
    'Andi Mack': 'TV',
    'Athletes': 'RPF/Sports',
    'BTS': 'Music/RPF',
    'Boku no Hero Academia': 'Anime/Manga',
    'Brooklyn Nine-Nine': 'TV',
    'Carry On': 'Books',
    'Druck': 'TV',
    'EXO': 'Music/RPF',
    'EastEnders': 'TV',
    'Emmerdale': 'TV',
    'Fairy Tail': 'Anime/Manga',
    'Fifth Harmony': 'Music/RPF',
    'Fire Emblem': 'Video Games',
    'Game of Thrones': 'Books/TV',
    'Good Omens': 'Books/TV',
    'Gotham': 'Comics/TV',
    'Grey\'s Anatomy': 'TV',
    'Hannibal': 'TV',
    'Homestuck': 'Webcomic',
    'How to Train Your Dragon': 'Animation/Movies',
    'Invader Zim': 'Animation',
    'It': 'Books/Movies',
    'Kingdom Hearts': 'Video Games',
    'Legacies': 'TV',
    'Merlin': 'TV',
    'Miraculous: Tales of Ladybug & Cat Noir': 'Animation',
    'Mo Dao Zu Shi': 'Anime/Books',
    'Mob Psycho 100': 'Anime/Manga',
    'Moominvalley': 'Animation',
    'Naruto': 'Anime/Manga',
    'OK K.O.! Let’s Be Heroes': 'Animation',
    'One Direction': 'Music/RPF',
    'Overwatch': 'Video Games',
    'Pitch Perfect': 'Movies',
    'RWBY': 'Animation',
    'Riverdale': 'Comics/TV',
    'Roswell, New Mexico': 'TV',
    'RuPaul\'s Drag Race': 'TV',
    'Runaways': 'Comics/TV',
    'SKAM España': 'TV',
    'SKAM France': 'TV',
    'SKAM Italia': 'TV',
    'Shadowhunters': 'Books/TV',
    'She-Ra and the Princesses of Power': 'Animation',
    'Sherlock': 'TV',
    'Star Trek': 'Movies/TV',
    'Star vs. the Forces of Evil': 'Animation',
    'Steven Universe': 'Animation',
    'Stranger Things': 'TV',
    'Supergirl': 'Comics/TV',
    'Supernatural': 'TV',
    'Teen Wolf': 'TV',
    'The 100': 'TV',
    'The Dragon Prince': 'Animation',
    'The Legend of Korra': 'Animation',
    'The Legend of Zelda': 'Video Games',
    'Thomas Sanders': 'Internet/RPF',
    'Voltron: Legendary Defender': 'Animation',
    'Wynonna Earp': 'Comics/TV',
    'YouTubers': 'Internet/RPF',
    'Yuri!!! on Ice': 'Anime',
    'actors': 'RPF',
    'celebrities': 'RPF',
    'the Harry Potter universe': 'Books/Movies',
    'the Marvel universe': 'Comics/Movies/TV',
    'the Star Wars universe': 'Movies/TV/Animation',
    },
    {# 2020
    '9-1-1': 'TV',
    '9-1-1: Lone Star': 'TV',
    'Ace Attorney': 'Video Games',
    'Actors': 'RPF',
    'Amar a muerte': 'TV',
    'Anne with an E': 'Books/TV',
    'Athletes': 'RPF/Sports',
    'Atypical': 'TV',
    'Avatar: The Last Airbender': 'Animation',
    'BTS': 'Music/RPF',
    'Boku no Hero Academia': 'Anime/Manga',
    'Brooklyn Nine-Nine': 'TV',
    'Carry On': 'Books',
    'Critical Role': 'TTRPG/TV',
    'Detroit: Become Human': 'Video Games',
    'EastEnders': 'TV',
    'Fairy Tail': 'Anime/Manga',
    'Fire Emblem': 'Video Games',
    'Frozen': 'Animation/Movies',
    'Frozen II': 'Animation/Movies',
    'Good Omens': 'Books/TV',
    'Haikyuu!!': 'Anime/Manga',
    'Half-Life VR but the AI is Self-Aware': 'Video Games',
    'Hannibal': 'TV',
    'Hazbin Hotel': 'Animation',
    'Homestuck': 'Webcomic',
    'It': 'Books/Movies',
    'Killing Eve': 'TV',
    'Lucifer': 'Comics/TV',
    'Merlin': 'TV',
    'Miraculous: Tales of Ladybug & Cat Noir': 'Animation',
    'Miraculous: Tales of Ladybug & Cat Noir x The DC Universe': 'Animation/Crossover',
    'Mo Dao Zu Shi': 'Anime/Books',
    'Naruto': 'Anime/Manga',
    'One Direction': 'Music/RPF',
    'Percy Jackson': 'Books/Movies',
    'Percy Jackson & the Olympians': 'Books/Movies',
    'RWBY': 'Animation',
    'Riverdale': 'Comics/TV',
    'Roswell, New Mexico': 'TV',
    'SKAM France': 'TV',
    'Shadowhunters': 'Books/TV',
    'Shameless': 'TV',
    'She-Ra and the Princesses of Power': 'Animation',
    'Sherlock': 'TV',
    'Star Trek': 'Movies/TV',
    'Steven Universe': 'Animation',
    'Stranger Things': 'TV',
    'Supergirl': 'Comics/TV',
    'Supernatural': 'TV',
    'Teen Wolf': 'TV',
    'The 100': 'TV',
    'The Dragon Prince': 'Animation',
    'The Legend of Korra': 'Animation',
    'The Legend of Zelda': 'Video Games',
    'The Magnus Archives': 'Podcast',
    'The Old Guard': 'Movies',
    'The Owl House': 'Animation',
    'The Raven Cycle': 'Books',
    'The Walking Dead': 'TV',
    'The Witcher': 'Books/TV/Video Games',
    'Thomas Sanders': 'Internet/RPF',
    'Voltron: Legendary Defender': 'Animation',
    'WTFock': 'TV',
    'Wynonna Earp': 'Comics/TV',
    'YouTubers': 'Internet/RPF',
    'actors': 'RPF',
    'celebrities': 'RPF',
    'the Final Fantasy franchise': 'Video Games',
    'the DC Universe': 'Comics/Movies/TV',
    'the Harry Potter universe': 'Books/Movies',
    'the Marvel universe': 'Comics/Movies/TV',
    'the Star Wars universe': 'Movies/TV/Animation',
    },
    {# 2021
    '9-1-1': 'TV',
    '9-1-1: Lone Star': 'TV',
    'Ace Attorney': 'Video Games',
    'Actors': 'RPF',
    'Adventure Time': 'Animation',
    'Athletes': 'RPF/Sports',
    'Attack on Titan': 'Anime/Manga',
    'Avatar: The Last Airbender': 'Animation',
    'BTS': 'Music/RPF',
    'Boku no Hero Academia': 'Anime/Manga',
    'Chicago P.D.': 'TV',
    'Critical Role': 'TTRPG/TV',
    'Danganronpa': 'Video Games',
    'Fairy Tail': 'Anime/Manga',
    'Good Omens': 'Books/TV',
    'Hades': 'Video Games',
    'Haikyuu!!': 'Anime/Manga',
    'Hannibal': 'TV',
    'Hanyō no Yashahime': 'Anime',
    'It': 'Books/Movies',
    'Jujutsu Kaisen': 'Anime/Manga',
    'Julie and the Phantoms': 'TV',
    'Loki': 'Comics/TV',
    'Luca': 'Animation/Movies',
    'Lucifer': 'Comics/TV',
    'Merlin': 'TV',
    'Miraculous: Tales of Ladybug & Cat Noir': 'Animation',
    'Miraculous: Tales of Ladybug & Cat Noir x The DC Universe': 'Animation/Crossover',
    'Mo Dao Zu Shi': 'Anime/Books',
    'Naruto': 'Anime/Manga',
    'RWBY': 'Animation',
    'Roswell, New Mexico': 'TV',
    'SK8 the Infinity': 'Anime',
    'Shadow and Bone': 'Books/TV',
    'Shameless': 'TV',
    'She-Ra and the Princesses of Power': 'Animation',
    'Sherlock': 'TV',
    'Singers': 'Music/RPF',
    'Star Trek': 'Movies/TV',
    'Star Wars: The Clone Wars': 'Animation',
    'Stranger Things': 'TV',
    'Streamers': 'Internet/RPF',
    'Supergirl': 'Comics/TV',
    'Supernatural': 'TV',
    'Teen Wolf': 'TV',
    'The Haunting of Bly Manor': 'TV',
    'The Legend of Korra': 'Animation',
    'The Legend of Zelda': 'Video Games',
    'The Magnus Archives': 'Podcast',
    'The Old Guard': 'Movies',
    'The Owl House': 'Animation',
    'The Rookie': 'TV',
    'The Witcher': 'Books/TV/Video Games',
    'Tian Guan Ci Fu': 'Anime/Books',
    'Voltron: Legendary Defender': 'Animation',
    'Word of Honor': 'TV',
    'Wynonna Earp': 'Comics/TV',
    'YouTubers': 'Internet/RPF',
    'the A Court of Thorns and Roses series': 'Books',
    'the DC Universe': 'Comics/Movies/TV',
    'the Harry Potter universe': 'Books/Movies',
    'the Marvel universe': 'Comics/Movies/TV',
    'the Percy Jackson universe': 'Books/Movies',
    'the Star Wars universe': 'Movies/TV/Animation',
    },
    {# 2022
    '9-1-1': 'TV',
    '9-1-1: Lone Star': 'TV',
    'Ace Attorney': 'Video Games',
    'Amphibia': 'Animation',
    'Arcane': 'Animation/Video Games',
    'Avatar: The Last Airbender': 'Animation',
    'BTS': 'Music/RPF',
    'Bad Buddy': 'TV',
    'Boku no Hero Academia': 'Anime/Manga',
    'Bridgerton': 'Books/TV',
    'Bungou Stray Dogs': 'Anime/Manga',
    'Critical Role': 'TTRPG/TV',
    'Deltarune': 'Video Games',
    'Doctor Who': 'TV',
    'Eternals': 'Comics/Movies',
    'Euphoria': 'TV',
    'First Kill': 'TV',
    'Good Omens': 'Books/TV',
    'Hannibal': 'TV',
    'Heartstopper': 'TV/Webcomic',
    'Helluva Boss': 'Animation/Web Series',
    'House of the Dragon': 'Books/TV',
    'Interview with the Vampire': 'Books/TV',
    'Jujutsu Kaisen': 'Anime/Manga',
    'Killing Eve': 'TV',
    'KinnPorsche': 'TV',
    'Merlin': 'TV',
    'Miraculous: Tales of Ladybug & Cat Noir': 'Animation',
    'Mo Dao Zu Shi': 'Anime/Books',
    'Mob Psycho 100': 'Anime/Manga',
    'Naruto': 'Anime/Manga',
    'Our Flag Means Death': 'TV',
    'RWBY': 'Animation',
    'Roswell, New Mexico': 'TV',
    'SPY x FAMILY': 'Anime/Manga',
    'Shadow and Bone': 'Books/TV',
    'She-Ra and the Princesses of Power': 'Animation',
    'Sherlock': 'TV',
    'Sonic the Hedgehog': 'Video Games',
    'Star Trek': 'Movies/TV',
    'Star Wars: The Clone Wars': 'Animation',
    'Stranger Things': 'TV',
    'Succession': 'TV',
    'Supergirl': 'Comics/TV',
    'Supernatural': 'TV',
    'Teen Wolf': 'TV',
    'The Batman': 'Comics/Movies',
    'The Legend of Korra': 'Animation',
    'The Legend of Zelda': 'Video Games',
    'The Locked Tomb series': 'Books',
    'The Magnus Archives': 'Podcast',
    'The Owl House': 'Animation',
    'The Rookie': 'TV',
    'The Sandman': 'Comics/TV',
    'The Witcher': 'Books/TV/Video Games',
    'Tian Guan Ci Fu': 'Anime/Books',
    'Voltron: Legendary Defender': 'Animation',
    'What We Do In The Shadows': 'TV',
    'actors': 'RPF',
    'streamers': 'Internet/RPF',
    'the DC Universe': 'Comics/Movies/TV',
    'the Harry Potter series': 'Books/Movies',
    'the Harry Potter universe': 'Books/Movies',
    'the Marvel universe': 'Comics/Movies/TV',
    'the Percy Jackson universe': 'Books/Movies',
    'the Star Wars universe': 'Animation/Movies/TV',
    },
    {# 2023
    '9-1-1': 'TV',
    '9-1-1: Lone Star': 'TV',
    'Ace Attorney': 'Video Games',
    'Actors': 'RPF',
    'Adventure Time': 'Animation',
    'Adventure Time: Fionna and Cake': 'Animation',
    'Arcane': 'Animation/Video Games',
    'Avatar: The Last Airbender': 'Animation',
    'Baldur’s Gate 3': 'Video Games',
    'Boku no Hero Academia': 'Anime/Manga',
    'Buddy Daddies': 'Anime',
    'Bungou Stray Dogs': 'Anime/Manga',
    'Chainsaw Man': 'Anime/Manga',
    'Critical Role': 'TTRPG/TV',
    'Formula 1 drivers': 'RPF/Sports',
    'Genshin Impact': 'Video Games',
    'Good Omens': 'Books/TV',
    'Hannibal': 'TV',
    'Heartstopper': 'TV/Webcomic',
    'Homestuck': 'Webcomic',
    'House of the Dragon': 'Books/TV',
    'Interview with the Vampire': 'Books/TV',
    'Jujutsu Kaisen': 'Anime/Manga',
    'Lego Monkie Kid': 'Animation',
    'Lockwood & Co.': 'Books/TV',
    'Merlin': 'TV',
    'Miraculous: Tales of Ladybug & Cat Noir': 'Animation',
    'Mo Dao Zu Shi': 'Anime/Books',
    'Mob Psycho 100': 'Anime/Manga',
    'Mobile Suit Gundam: The Witch from Mercury': 'Anime',
    'Naruto': 'Anime/Manga',
    'Nimona': 'Comics/Movies',
    'One Piece': 'Anime/Manga',
    'Our Flag Means Death': 'TV',
    'Persona 5': 'Video Games',
    'RWBY': 'Animation',
    'Red, White & Royal Blue': 'Books/Movies',
    'SPY x FAMILY': 'Anime/Manga',
    'She-Ra and the Princesses of Power': 'Animation',
    'Sherlock': 'TV',
    'Sonic the Hedgehog': 'Video Games',
    'South Park': 'Animation',
    'Spider-Man: Across the Spider-Verse': 'Comics/Movies',
    'Star Trek': 'Movies/TV',
    'Star Wars: The Clone Wars': 'Animation',
    'Stranger Things': 'TV',
    'Streamers': 'Internet/RPF',
    'Succession': 'TV',
    'Supergirl': 'Comics/TV',
    'Supernatural': 'TV',
    'Teen Wolf': 'TV',
    'The Last of Us': 'TV/Video Games',
    'The Legend of Korra': 'Animation',
    'The Legend of Zelda': 'Video Games',
    'The Locked Tomb series': 'Books',
    'The Magnus Archives': 'Podcast',
    'The Owl House': 'Animation',
    'The Rookie': 'TV',
    'The Sandman': 'Comics/TV',
    'The Witcher': 'Books/TV/Video Games',
    'Tian Guan Ci Fu': 'Anime/Books',
    'Trigun Stampede': 'Anime',
    'Voltron: Legendary Defender': 'Animation',
    'Warrior Nun': 'TV',
    'Am-Diaz & Prince Henry of Wales, Red': 'Books/Movies',
    'Red, White & Royal Blue': 'Books/Movies',
    'Wednesday': 'TV',
    'What We Do in the Shadows': 'TV',
    'Young Justice': 'Animation/Comics',
    'Young Royals': 'TV',
    'the Call of Duty franchise': 'Video Games',
    'the DC universe': 'Comics/Movies/TV',
    'the Grishaverse': 'Books/TV',
    'the Harry Potter universe': 'Books/Movies',
    'the Marvel universe': 'Comics/Movies/TV',
    'the Percy Jackson universe': 'Books/Movies',
    'the Pokémon franchise': 'Anime/Video Games',
    'the Star Wars universe': 'Movies/TV/Animation',
    'the Super Mario Bros. franchise': 'Video Games',
    },
    {# 2024
    '9-1-1': 'TV',
    'Ace Attorney': 'Video Games',
    'An Extremely Goofy Movie': 'Animation',
    'Arcane': 'Animation/Video Games',
    'Avatar: The Last Airbender': 'Animation',
    'Baldur\'s Gate 3': 'Video Games',
    'Boku no Hero Academia': 'Anime/Manga',
    'Bridgerton': 'Books/TV',
    'Bungou Stray Dogs': 'Anime/Manga',
    'Critical Role': 'TTRPG/TV',
    'Cult of the Lamb': 'Video Games',
    'Dead Boy Detectives': 'Comics/TV',
    'Disco Elysium': 'Video Games',
    'Dungeon Meshi': 'Anime/Manga',
    'Formula 1 drivers': 'RPF/Sports',
    'Genshin Impact': 'Video Games',
    'Good Omens': 'Books/TV',
    'Gravity Falls': 'Animation',
    'Hannibal': 'TV',
    'Hazbin Hotel': 'Animation',
    'Helluva Boss': 'Animation/Web Series',
    'Homestuck': 'Webcomic',
    'Honkai: Star Rail': 'Video Games',
    'House': 'TV',
    'House of the Dragon': 'Books/TV',
    'Interview with the Vampire': 'Books/TV',
    'Jujutsu Kaisen': 'Anime/Manga',
    'Lego Monkie Kid': 'Animation',
    'Loki': 'Comics/TV',
    'Merlin': 'TV',
    'Miraculous: Tales of Ladybug & Cat Noir': 'Animation',
    'Mo Dao Zu Shi': 'Anime/Books',
    'Mortal Kombat': 'Movies/Video Games',
    'Murder Drones': 'Animation',
    'One Piece': 'Anime/Manga',
    'Our Flag Means Death': 'TV',
    'Persona 5': 'Video Games',
    'Puella Magi Madoka Magica': 'Anime',
    'Red, White & Royal Blue': 'Books/Movies',
    'SPY x FAMILY': 'Anime/Manga',
    'Saw': 'Movies',
    'Sonic the Hedgehog': 'Video Games',
    'Splatoon': 'Video Games',
    'Star Trek': 'Movies/TV',
    'Stranger Things': 'TV',
    'Supernatural': 'TV',
    'The Amazing Digital Circus': 'Animation',
    'The Hunger Games': 'Books/Movies',
    'The Legend of Korra': 'Animation',
    'The Legend of Zelda': 'Video Games',
    'The Locked Tomb series': 'Books',
    'The Magnus Archives': 'Podcast',
    'The Owl House': 'Animation',
    'The Scum Villain\'s Self-Saving System': 'Books',
    'The Scott Pilgrim franchise': 'Comics/Movies',
    'Tian Guan Ci Fu': 'Anime/Books',
    'Transformers': 'Animation/Movies',
    'Trigun': 'Anime/Manga',
    'Voltron: Legendary Defender': 'Animation',
    'Wednesday': 'TV',
    'Young Justice': 'Animation/Comics',
    'Young Royals': 'TV',
    'YouTubers': 'Internet/RPF',
    'the Call of Duty franchise': 'Video Games',
    'the DC universe': 'Comics/Movies/TV',
    'the Harry Potter universe': 'Books/Movies',
    'the Marvel universe': 'Comics/Movies/TV',
    'the Percy Jackson universe': 'Books/Movies',
    'the Pokémon franchise': 'Anime/Video Games',
    'the Trolls franchise': 'Animation/Movies',
}
]

def generate_master_config(config_list):
    """
    Combines all dictionaries in the list into a single dictionary.
    Later entries overwrite earlier ones, ensuring corrections take precedence.
    """
    master_dict = {}
    for config_dict in config_list:
        master_dict.update(config_dict)
    return master_dict

# this is the dictionary other files use
FANDOM_CATEGORIES = generate_master_config(FANDOM_CATEGORIES_BY_YEAR)